#! /bin/sh
# Test atexit handling.
#
# Copyright (C) 2019-2026 Free Software Foundation, Inc.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

. "${srcdir=.}/tests/init.sh"; path_prepend_ .

if ! test -w /dev/full || ! test -c /dev/full; then
  skip_ '/dev/full is required'
fi

returns_ 1 hello >/dev/full 2>err || fail=1
grep "^hello: write error" err || fail=1

Exit $fail
