#! /bin/sh
# Test arbitrary --greeting.
#
# Copyright (C) 2001-2026 Free Software Foundation, Inc.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

. "${srcdir=.}/tests/init.sh"; path_prepend_ .

# No locale settings in this test, since we are using a fixed string;
# nothing in the output should be locale-dependent.

cat <<EOF >exp || framework_failure_
Nothing happens here.
EOF
hello -g 'Nothing happens here.' >out || fail=1
compare exp out || fail=1

Exit $fail
