#! /bin/sh
# Test standard GNU greeting.
#
# Copyright (C) 2001-2026 Free Software Foundation, Inc.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.
# This script takes one argument.

. "${srcdir=.}/tests/init.sh"; path_prepend_ .

cat <<EOF >exp || framework_failure_
Hello, world!
EOF
hello >out || fail=1
compare exp out || fail=1

Exit $fail
