#! /bin/sh
# Test extra operands fail correct way.
#
# Copyright (C) 2019-2026 Free Software Foundation, Inc.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

. "${srcdir=.}/tests/init.sh"; path_prepend_ .

cat <<EOF >exp || framework_failure_
hello: extra operand: first
Try 'hello --help' for more information.
EOF
returns_ 1 hello first second 2>err
compare exp err || fail=1

Exit $fail
